-- 00001_initial_schema.sql
-- Initial database schema for Argus (Bundle ID: com.signode.argus)

-- =========================================================================
-- 1. Custom Enum Types
-- =========================================================================

CREATE TYPE user_role AS ENUM ('staff', 'line_owner', 'supervisor', 'quality_manager', 'admin');
CREATE TYPE ticket_status AS ENUM ('open', 'assigned', 'in_progress', 'resolved', 'closed');
CREATE TYPE ticket_severity AS ENUM ('critical', 'major', 'minor');

-- =========================================================================
-- 2. Sequences
-- =========================================================================

-- Sequence for autoincrementing human-readable ticket IDs
CREATE SEQUENCE ticket_seq START 1;

-- =========================================================================
-- 3. Core Database Tables
-- =========================================================================

-- 3.1 Plants
CREATE TABLE public.plants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.2 Lines
CREATE TABLE public.lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plant_id uuid NOT NULL REFERENCES public.plants(id) ON DELETE CASCADE,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.3 Stations
CREATE TABLE public.stations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  line_id uuid NOT NULL REFERENCES public.lines(id) ON DELETE CASCADE,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.4 Defect Categories
CREATE TABLE public.defect_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.5 Users (Synchronized profile extension of auth.users)
CREATE TABLE public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  name text NOT NULL,
  role user_role NOT NULL DEFAULT 'staff',
  plant_id uuid REFERENCES public.plants(id) ON DELETE SET NULL,
  line_id uuid REFERENCES public.lines(id) ON DELETE SET NULL,
  shift text,
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.6 Tickets
CREATE TABLE public.tickets (
  id text PRIMARY KEY, -- Formatted like ARG-2026-00042 (Generated by Trigger)
  reporter_id uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  line_id uuid NOT NULL REFERENCES public.lines(id) ON DELETE RESTRICT,
  station_id uuid NOT NULL REFERENCES public.stations(id) ON DELETE RESTRICT,
  defect_category_id uuid NOT NULL REFERENCES public.defect_categories(id) ON DELETE RESTRICT,
  severity ticket_severity NOT NULL,
  photos text[] NOT NULL DEFAULT '{}',
  voice_note_url text,
  description text NOT NULL,
  status ticket_status NOT NULL DEFAULT 'open',
  assigned_owner_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  offline_id uuid UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  acknowledged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  closed_at timestamp with time zone,
  root_cause text,
  corrective_action text
);

-- 3.7 Ticket Events (Audit Trail Logs)
CREATE TABLE public.ticket_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id text NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  event_type text NOT NULL,
  old_value text,
  new_value text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.8 Assignment Rules
CREATE TABLE public.assignment_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  line_id uuid NOT NULL REFERENCES public.lines(id) ON DELETE CASCADE,
  defect_category_id uuid NOT NULL REFERENCES public.defect_categories(id) ON DELETE CASCADE,
  shift text,
  assigned_owner_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.9 SLA Targets
CREATE TABLE public.sla_targets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  severity ticket_severity NOT NULL UNIQUE,
  target_minutes integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.10 Notification Logs
CREATE TABLE public.notifications_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  ticket_id text REFERENCES public.tickets(id) ON DELETE SET NULL,
  title text NOT NULL,
  body text NOT NULL,
  sent_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 4. Helper & Security Functions
-- =========================================================================

-- Safe role resolver to prevent circular dependencies in RLS policies
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS user_role SECURITY DEFINER AS $$
DECLARE
  my_role user_role;
BEGIN
  SELECT role INTO my_role FROM public.users WHERE id = auth.uid();
  RETURN coalesce(my_role, 'staff'::user_role);
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- 5. PostgreSQL Triggers & Handlers
-- =========================================================================

-- 5.1 Ticket ID Generator Trigger
CREATE OR REPLACE FUNCTION public.trg_generate_ticket_id()
RETURNS TRIGGER AS $$
DECLARE
  year_str text;
  seq_str text;
BEGIN
  IF NEW.id IS NULL OR NEW.id = '' THEN
    year_str := to_char(CURRENT_DATE, 'YYYY');
    seq_str := lpad(nextval('ticket_seq')::text, 5, '0');
    NEW.id := 'ARG-' || year_str || '-' || seq_str;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_ticket_id
BEFORE INSERT ON public.tickets
FOR EACH ROW
EXECUTE FUNCTION public.trg_generate_ticket_id();

-- 5.2 Ticket Audit Trail Trigger
CREATE OR REPLACE FUNCTION public.trg_audit_ticket_changes()
RETURNS TRIGGER AS $$
DECLARE
  actor_id_val uuid;
BEGIN
  -- Extract actor UUID from transaction request context or fallback to reporter
  BEGIN
    actor_id_val := coalesce(
      nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::uuid,
      NEW.reporter_id
    );
  EXCEPTION WHEN OTHERS THEN
    actor_id_val := NEW.reporter_id;
  END;

  IF OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO public.ticket_events (ticket_id, actor_id, event_type, old_value, new_value)
    VALUES (NEW.id, actor_id_val, 'status_change', OLD.status::text, NEW.status::text);
  END IF;

  IF OLD.severity IS DISTINCT FROM NEW.severity THEN
    INSERT INTO public.ticket_events (ticket_id, actor_id, event_type, old_value, new_value)
    VALUES (NEW.id, actor_id_val, 'severity_change', OLD.severity::text, NEW.severity::text);
  END IF;

  IF OLD.assigned_owner_id IS DISTINCT FROM NEW.assigned_owner_id THEN
    INSERT INTO public.ticket_events (ticket_id, actor_id, event_type, old_value, new_value)
    VALUES (NEW.id, actor_id_val, 'assignment_change', OLD.assigned_owner_id::text, NEW.assigned_owner_id::text);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER audit_ticket_changes
AFTER UPDATE ON public.tickets
FOR EACH ROW
EXECUTE FUNCTION public.trg_audit_ticket_changes();

-- 5.3 Updated At Auto-Maintenance Trigger
CREATE OR REPLACE FUNCTION public.trg_update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_plants_updated_at BEFORE UPDATE ON public.plants FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_lines_updated_at BEFORE UPDATE ON public.lines FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_stations_updated_at BEFORE UPDATE ON public.stations FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_defect_categories_updated_at BEFORE UPDATE ON public.defect_categories FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_tickets_updated_at BEFORE UPDATE ON public.tickets FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_assignment_rules_updated_at BEFORE UPDATE ON public.assignment_rules FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();
CREATE TRIGGER update_sla_targets_updated_at BEFORE UPDATE ON public.sla_targets FOR EACH ROW EXECUTE FUNCTION public.trg_update_updated_at();

-- 5.4 Automatic auth.users -> public.users Profile Generator Sync
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, name, role, is_active)
  VALUES (
    NEW.id,
    NEW.email,
    coalesce(NEW.raw_user_meta_data->>'name', 'QC Operator'),
    coalesce((NEW.raw_user_meta_data->>'role')::public.user_role, 'staff'::public.user_role),
    true
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================================
-- 6. Performance Indexing
-- =========================================================================

CREATE INDEX idx_tickets_line_status ON public.tickets(line_id, status);
CREATE INDEX idx_tickets_created_at_desc ON public.tickets(created_at DESC);
CREATE INDEX idx_tickets_assigned_owner ON public.tickets(assigned_owner_id);
CREATE INDEX idx_assignment_rules_line_cat_shift ON public.assignment_rules(line_id, defect_category_id, shift);
CREATE INDEX idx_ticket_events_ticket_created_desc ON public.ticket_events(ticket_id, created_at DESC);

-- =========================================================================
-- 7. Row-Level Security (RLS) & Policies
-- =========================================================================

-- Enable RLS across all tables
ALTER TABLE public.plants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.defect_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sla_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications_log ENABLE ROW LEVEL SECURITY;

-- 7.1 Static Reference Data RLS (Read for all authenticated, modify for Admins/QMs)

-- Plants
CREATE POLICY select_auth ON public.plants FOR SELECT TO authenticated USING (true);
CREATE POLICY modify_admin_qm ON public.plants FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- Lines
CREATE POLICY select_auth ON public.lines FOR SELECT TO authenticated USING (true);
CREATE POLICY modify_admin_qm ON public.lines FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- Stations
CREATE POLICY select_auth ON public.stations FOR SELECT TO authenticated USING (true);
CREATE POLICY modify_admin_qm ON public.stations FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- Defect Categories
CREATE POLICY select_auth ON public.defect_categories FOR SELECT TO authenticated USING (true);
CREATE POLICY modify_admin_qm ON public.defect_categories FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- SLA Targets
CREATE POLICY select_auth ON public.sla_targets FOR SELECT TO authenticated USING (true);
CREATE POLICY modify_admin_qm ON public.sla_targets FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- Assignment Rules
CREATE POLICY select_auth ON public.assignment_rules FOR SELECT TO authenticated USING (true);
CREATE POLICY modify_admin_qm ON public.assignment_rules FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- 7.2 User Profiles RLS
CREATE POLICY select_auth ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY update_own ON public.users FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY admin_all ON public.users FOR ALL TO authenticated USING (get_my_role() = 'admin') WITH CHECK (get_my_role() = 'admin');

-- 7.3 Ticket Management RLS
-- Global Read/Write for Quality Managers and Admins
CREATE POLICY select_admin_qm ON public.tickets FOR SELECT TO authenticated USING (get_my_role() IN ('admin', 'quality_manager'));
CREATE POLICY write_admin_qm ON public.tickets FOR ALL TO authenticated USING (get_my_role() IN ('admin', 'quality_manager')) WITH CHECK (get_my_role() IN ('admin', 'quality_manager'));

-- Staff read tickets on their line and create tickets
CREATE POLICY select_staff ON public.tickets FOR SELECT TO authenticated USING (
  get_my_role() = 'staff' AND line_id = (SELECT line_id FROM public.users WHERE id = auth.uid())
);
CREATE POLICY insert_staff ON public.tickets FOR INSERT TO authenticated WITH CHECK (
  get_my_role() = 'staff' AND reporter_id = auth.uid()
);

-- Department Leads (Line Owners, Supervisors) read and update tickets on their line, assigned to them, or matching assignment rules
CREATE POLICY select_leads ON public.tickets FOR SELECT TO authenticated USING (
  get_my_role() IN ('line_owner', 'supervisor') AND (
    line_id = (SELECT line_id FROM public.users WHERE id = auth.uid()) OR
    assigned_owner_id = auth.uid() OR
    EXISTS (
      SELECT 1 FROM public.assignment_rules
      WHERE assignment_rules.assigned_owner_id = auth.uid()
        AND assignment_rules.line_id = tickets.line_id
        AND assignment_rules.defect_category_id = tickets.defect_category_id
    )
  )
);
CREATE POLICY update_leads ON public.tickets FOR UPDATE TO authenticated USING (
  get_my_role() IN ('line_owner', 'supervisor') AND (
    line_id = (SELECT line_id FROM public.users WHERE id = auth.uid()) OR
    assigned_owner_id = auth.uid() OR
    EXISTS (
      SELECT 1 FROM public.assignment_rules
      WHERE assignment_rules.assigned_owner_id = auth.uid()
        AND assignment_rules.line_id = tickets.line_id
        AND assignment_rules.defect_category_id = tickets.defect_category_id
    )
  )
) WITH CHECK (
  get_my_role() IN ('line_owner', 'supervisor')
);

-- 7.4 Ticket Events (Selectable if user can select parent ticket)
CREATE POLICY select_events ON public.ticket_events FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.tickets
    WHERE tickets.id = ticket_events.ticket_id
  )
);

-- 7.5 Notification Logs (Selectable only for owner recipient)
CREATE POLICY select_own ON public.notifications_log FOR SELECT TO authenticated USING (user_id = auth.uid());

-- =========================================================================
-- 8. Database Webhooks for Edge Functions
-- =========================================================================

-- Enable pg_net extension to support asynchronous HTTP POST webhook triggers
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- Handler function to forward ticket creation events to the auto-assign Edge Function
CREATE OR REPLACE FUNCTION public.trg_webhook_auto_assign()
RETURNS trigger AS $$
BEGIN
  PERFORM
    net.http_post(
      url := coalesce(
        nullif(current_setting('custom.supabase_url', true), ''),
        'http://localhost:54321'
      ) || '/functions/v1/auto-assign-ticket',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || coalesce(nullif(current_setting('custom.service_role_key', true), ''), 'service-key')
      ),
      body := jsonb_build_object(
        'type', TG_OP,
        'table', TG_TABLE_NAME,
        'schema', TG_TABLE_SCHEMA,
        'record', row_to_json(NEW)
      )
    );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind webhook trigger to tickets table after insert events
CREATE OR REPLACE TRIGGER on_ticket_created
  AFTER INSERT ON public.tickets
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_webhook_auto_assign();

-- =========================================================================
-- 9. API Schema Permissions & Default Privileges
-- =========================================================================

-- Grant usage on public schema to standard Supabase roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;

-- Grant all permissions on existing public schema objects
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- Ensure future public schema objects inherit all permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres, anon, authenticated, service_role;
