name: argus_ui
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: ^2.1.0
  google_fonts: ^6.2.1
  argus_core:
    path: ../argus_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Variable.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
